# spring.active.profiles=prod 일 경우 설정
spring:
    datasource:
        url: jdbc:mysql://codeunicorn-database.chixb4yggzph.ap-northeast-2.rds.amazonaws.com:3306/codeunicorn?serverTimezone=Asia/Seoul
        username: admin
        password: "adapterz^&*1"
        driver-class-name: com.mysql.cj.jdbc.Driver
hibernate:
    ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
cloud:
    aws:
        credentials:
            accessKey: AKIAYZSNITCOEMFMLYB4
            secretKey: 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
        s3:
            bucket: code-unicorn-service
            dir: images
        region:
            static: ap-northeast-2
        stack:
            auto: false
