# spring.active.profiles=prod 일 경우 설정
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/prod?serverTimezone=Asia/Seoul # localhost:3306//{DB명}
        username: # 계정명
        password: # 비밀번호
        driver-class-name: com.mysql.cj.jdbc.Driver
hibernate:
    ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
cloud:
    aws:
        credentials:
            accessKey: AKIAYZSNITCOEMFMLYB4
            secretKey: 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
        s3:
            bucket: code-unicorn-service
            dir: images
        region:
            static: ap-northeast-2
        stack:
            auto: false
