server:
    port: 8080
    tomcat:
        uri-encoding: UTF-8
spring:
    application:
        name: CODE_UNICORN
    jpa:
        hibernate:
            ddl-auto: update # 빌드 후, model 에 있는 파일을 읽고 DB에 스키마를 자동으로 생성
            use-new-id-generator-mappings: true
        show-sql: true # 실행되는 쿼리문을 보여줌
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect # 테이블 생성 시 엔진을 InnoDB로 생성
                format_sql: true # SQL 을 좀 더 예쁘게 출력하고 싶다
        session:
            timeout: 86400 # 세션 기간 하루로 설정
            store-type: jdbc
            jdbc.initialize-schema: always
logging:
    org:
        hibernate:
            SQL: DEBUG # logs the SQL queries
            type:
                descriptor:
                    sql:
                        BasicBinder: TRACE # logs the prepared statement parameters
