### spring.active.profiles=local 일 경우 설정
spring:
    datasource:
        url: jdbc:log4jdbc:mysql://localhost:3306/code_unicorn_local?serverTimezone=Asia/Seoul # localhost:3306//{DB명}
        username: root # 계정명
        password: "!Kokb9236..." # 비밀번호
        #        url: jdbc:log4jdbc:mysql://codeunicorn-database.chixb4yggzph.ap-northeast-2.rds.amazonaws.com:3306/codeunicorn?serverTimezone=Asia/Seoul
        #        username: admin
        #        password: "adapterz^&*1"
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
hibernate:
    ejb:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy # 카멜 타입인 변수명과 언더바를 이용하는 컬럼명 사이의 불일치 해결
cloud:
    aws:
        credentials:
            accessKey: AKIAYZSNITCOEMFMLYB4  # 엑세스 키 ID (AWS S3에서 발급 받은 키)
            secretKey: LjsCVugB1mTGQSp4EU2XxcnMuYOeH3IjkRWVFHPf  # 비밀 엑세스 키 ID (AWS S3에서 발급 받은 키)
        s3:
            bucket: code-unicorn-service # 버킷이름 (자신이 설정한 버킷이름)
            dir: images
        region:
            static: ap-northeast-2 # 버킷 지역(서울은 ap-northeast-2)
        stack:
            auto: false
