# spring.active.profiles=prod 일 경우 설정
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/prod?serverTimezone=Asia/Seoul # localhost:3306//{DB명}
        username: # 계정명
        password: # 비밀번호
        driver-class-name: com.mysql.cj.jdbc.Driver
